flask_sample/views/sample.py
from flask import Blueprint, redirect, request, render_template, url_for, flash

from sql.db import DB
sample = Blueprint('sample', __name__, url_prefix='/sample')


@sample.route('/add', methods=['GET', 'POST'])
def add():
    k = request.form.get("key", None)
    v = request.form.get("value", None)
    if k and v:
        try:
            result = DB.insertOne(
                "INSERT INTO IS601_Sample (name, val) VALUES(%s, %s)", k, v)
            if result.status:
                flash("Created Record", "success")
        except Exception as e:
            # TODO make this user-friendly
            flash(str(e), "danger")

    return render_template("add_sample.html")

@sample.route('/list', methods=['GET'])
def list():
    key = request.args.get("name")
    col = request.args.get("col")
    order = request.args.get("order")
    limit = request.args.get("limit", 10)
    args = []
    print(f"col {col} order {order}")
    # dynamically build our query and data mappings
    # use the WHERE true trick so we can easily append conditions without caring if a condition
    # already was applied (no need to check if WHERE exists)
    query = "SELECT id, name, val, created, modified from IS601_Sample WHERE 1=1"
    if key:
        query += " AND name like %s"
        args.append(f"%{key}%")
    if col and order:
        # incorrect
        # these get passed as safe strings rather than sql keywords
        # query += f" ORDER BY %s %s"
        # args.append(col)
        # args.append(order)
        # correct - validate fully that col and order are expected values
        # this will be directly injected and if not validated could
        # lead to sql injection
        if col in ["name","val","created","modified"] \
            and order in ["asc", "desc"]:
            query += f" ORDER BY {col} {order}"

    if limit and int(limit) > 0 and int(limit) <= 100:
        # technically this should follow the same rules as col/order
        # but it seems to work with the placeholder mapping with
        # this connector
        query += " LIMIT %s"
        args.append(int(limit))
    rows = []
    try:
        # convert our list to args via *
        print(query)
        resp = DB.selectAll(query, *args)
        if resp.status:
            rows = resp.rows
    except Exception as e:
        # TODO make this user-friendly
        flash(str(e), "danger")
    
    return render_template("list_sample.html", resp=rows)

@sample.route("/edit", methods=["GET", "POST"])
def edit():
    id = request.args.get("id")
    row = None
    if id is None:
        flash("ID is missing", "danger")
        return redirect(url_for("sample.list"))
    else:
        if request.method == "POST" and request.form.get("value"):
            val = request.form.get("value")
            try:
                result = DB.update("UPDATE IS601_Sample SET val = %s WHERE id = %s", val, id)
                if result.status:
                    flash("Updated record", "success")
            except Exception as e:
                # TODO make this user-friendly
                flash(e, "danger")
        try:
            result = DB.selectOne("SELECT name, val FROM IS601_Sample WHERE id = %s", id)
            if result.status:
                row = result.row
        except Exception as e:
            # TODO make this user-friendly
            flash(e, "danger")
    return render_template("edit_sample.html", row=row)

@sample.route("/delete", methods=["GET"])
def delete():
    id = request.args.get("id")
    if not id:
        flash("ID must be set", "danger")

    # make a mutable dict
    args = {**request.args}
    if id:
        try:
            result = DB.delete("DELETE FROM IS601_Sample WHERE id = %s", id)
            if result.status:
                flash("Deleted record", "success")
        except Exception as e:
            # TODO make this user-friendly
            flash(e, "danger")
        # TODO pass along feedback

        # remove the id args since we don't need it in the list route
        # but we want to persist the other query args
        del args["id"]
    return redirect(url_for("sample.list", **args))

flask_sample/templates/401.html
{% extends "layout.html" %}
{% block title %}403 - Access Denied{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header bg-warning text-black">
                    <h1 class="text-center">401 - Access Denied</h1>
                </div>
                <div class="card-body">
                    <p class="card-text">You need to login to access this resource.</p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

flask_sample/templates/_dropdown_nav.html
{% macro dropdown_nav(name, links) %}

<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
        aria-expanded="false">
        {{name}}
    </a>
    <ul class="dropdown-menu">
        {% for url, text in links %}
        <!-- assumes url is a route and text is a string-->
        <li><a class="dropdown-item" href="{{url_for(url)}}">{{text}}</a></li>
        {% endfor %}
    </ul>
</li>
{% endmacro %}

flask_sample/templates/_formhelpers.html
{% macro render_field(field) %}
{# demonstrating a macro (basically a template function)
modified from https://flask.palletsprojects.com/en/2.2.x/patterns/wtforms/
hints: https://gist.github.com/pwalsh/d3eb06ad098abcc9cb1d
#}
{% if field.type == "BooleanField" %}
<!-- handle checkbox/boolean field-->
<div class="form-check">
    {{field(class="form-check-input")}}
    {{ field.label(class="form-check-label")}}

</div>
{% else %}
<!-- handle other fields (todo implement other non-standard fields)-->
<div class="form-group mb-3">

    {{ field.label(class="form-label") }}
    {{ field(class="form-control",**kwargs)|safe }}
    
    {% if field.errors %}
    <ul class="errors">
        {% for error in field.errors %}
        <li class="text-danger">{{ error }}</li>
        {% endfor %}
    </ul>
    {% endif %}
</div>
{% endif %}
{% endmacro %}

flask_sample/templates/_table_helper.html
{% macro render_table(data, title=None, ignored=[], view=None, edit=None, delete=None, table_class="") %}
<div class="container-fluid">
    {% if title %}
    <div class="h1">{{ title }}</div>
    {% endif %}
    <table class="table {{ table_class }}">
        <thead>
            {% if data and data|length > 0 %}
            <tr class="text-capitalize">
                {% for r in data[0] %}
                {% if r not in ignored %}
                <th>{{ r }}</th>
                {% endif %}
                {% endfor %}
                {% if view or edit or delete %}
                <th>Actions</th>
                {% endif %}
            </tr>
            {% endif %}
        </thead>
        <tbody>
            {% for r in data %}
            <tr>
                {% for k, v in r.items() %}
                {% if k not in ignored %}
                <td>{{ v }}</td>
                {% endif %}
                {% endfor %}
                {% if view or edit or delete %}
                <td>
                    {% if view and r["id"] %}
                    <a href="{{ url_for(view) }}?id={{ r['id'] }}">View</a>
                    {% endif %}
                    {% if edit and r["id"] %}
                    <a href="{{ url_for(edit) }}?id={{ r['id'] }}">Edit</a>
                    {% endif %}
                    {% if delete and r["id"] %}
                    <a href="{{ url_for(delete) }}?id={{ r['id'] }}">Delete</a>
                    {% endif %}
                </td>
                {% endif %}
            </tr>
            {% endfor %}
            {% if not data %}
            <tr>
                <td colspan="100%">No results</td>
            </tr>
            {% endif %}
        </tbody>
    </table>
</div>
{% endmacro %}

flask_sample/templates/add_sample.html
{% extends "layout.html" %}
{% block title %}Add Sample{% endblock %}
{% block head %}
{{ super() }}
{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="h1">Add Sample</div>
    <div>
        <form method="POST">
            <div class="form-group mb-3">
                <label class="form-label" for="n">Key</label>
                <input class="form-control" id="n" name="key" />
            </div>
            <div class="form-group mb-3">
                <label class="form-label" for="v">Value</label>
                <input class="form-control" id="v" name="value" />
            </div>
            <input type="submit" class="btn btn-primary" value="Save Sample" />
        </form>
        {% if resp %}
        <div id="output">
            {{resp}}
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

flask_sample/templates/edit_sample.html
{% extends "layout.html" %}
{% block title %}Edit Sample{% endblock %}
{% block head %}
{{ super() }}
{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="h1">Edit Sample</div>
    <div>
        <form method="POST">
            <div class="form-group mb-3">
                <label class="form-label" for="n">Key</label>
                <input class="form-control" id="n" name="key" readonly value="{{row.name}}" />
            </div>
            <div class="form-group mb-3">
                <label class="form-label" for="v">Value</label>
                <input class="form-control" id="v" name="value" value="{{row.val}}" />
            </div>
            <input type="submit" class="btn btn-primary" value="Update Sample" />
        </form>
        {% if resp %}
        <div id="output">
            {{resp}}
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

flask_sample/templates/flash.html
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
<div id="flash-messages" class=flashes>
    {% for category, message in messages %}
    <div class="alert alert-{{ category or 'info' }}" role="alert" data-flash-id="{{ loop.index }}">{{ message }}</div>
    {% endfor %}
</div>
{% endif %}
{% endwith %}

<!-- Add this script to the end of your HTML body or in a separate JavaScript file -->
<script>
    // Function to hide flash messages after a delay
    function hideFlashMessages() {
      var flashMessages = document.getElementById('flash-messages');
      if (flashMessages) {
        // Get all flash messages with a data-flash-id attribute
        var messages = flashMessages.querySelectorAll('[data-flash-id]');
  
        // Set a timeout to hide each message after 3 seconds
        messages.forEach(function (message) {
          var flashId = message.getAttribute('data-flash-id');
          setTimeout(function () {
            var messageToRemove = document.querySelector('[data-flash-id="' + flashId + '"]');
            if (messageToRemove) {
              messageToRemove.remove(); // or use display: none; if you want to keep the element in the DOM
            }
          }, 2000); // Adjust the delay (in milliseconds) as needed
        });
      }
    }
  
    // Call the function when the page loads
    document.addEventListener('DOMContentLoaded', function () {
      hideFlashMessages();
    });
  </script>
  

flask_sample/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block head %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
            crossorigin="anonymous"></script>
        <link rel="icon" href="https://t3.ftcdn.net/jpg/04/54/66/12/240_F_454661277_NtQYM8oJq2wOzY1X9Y81FlFa06DVipVD.jpg" type="image/x-icon">
        <style>
            body {
                background-color: rgb(229, 209, 239);
                font-family: 'Arial', sans-serif; /* Change the font-family as needed */
            }

            .footer {
                position: absolute;
                bottom: 0;
                width: 100%;
                height: 60px;
                line-height: 60px;
                background-color: rgb(146, 220, 247);
            }

            .header {
                top: 0;
                height: 60px;
                line-height: 60px;
                background-color: rgb(146, 220, 247);
            }
        </style>
        <title>{% block title %}Music{% endblock %}</title>
    {% endblock %}
</head>

<body>
    <div id="header">
        {% include 'nav.html' %}
        {% include 'flash.html' %}
        <style>
            label {
                text-transform: capitalize;
            }
        </style>
    </div>
    <div id="content" class="overflow-auto" style="height: 84vh">{% block content %}{% endblock %}</div>
    <div id="footer" class="footer text-center fixed-bottom">
        {% block footer %}
            &copy; Copyright 2023.
        {% endblock %}
    </div>
</body>

</html>

flask_sample/templates/list_sample.html
{% extends "layout.html" %}
{% block title %}List Samples{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="h1">List Samples</div>
    <form class="row row-cols-lg-auto g-3 align-items-center">
        <div class="col-12">
            <label class="form-label" for="name">Name/Key</label>
            <input type="text" name="name" class="form-control" id="name" placeholder="name/key"
                value="{{request.args.get('name') or ''}}">
        </div>
        <div class="col-12">
            {% set options = ["name", "val", "modified", "created"] %}
            <label class="form-label" for="col">Column</label>
            {# notice value doesn't work for server-side built selects
            that's because the value is set before the options exist so it doesn't pick the proper
            option, instead we need to manually select the correct option or use a JS hack #}
            <select class="form-select" id="col" name="col" value="{{request.args.get('col')}}">
                <option value="">Choose...</option>
                {% for op in options %}
                {# using an inline if to output the selected attribute if it matches the op #}
                <option {{'selected' if request.args.get('col')==op }} value="{{op}}">{{op|capitalize}}</option>
                {% endfor %}
            </select>
        </div>
        <div class="col-12">
            <label class="form-label" for="order">Order</label>
            <select class="form-select" id="order" name="order" value="{{request.args.get('order')}}">
                <option value="">Choose...</option>
                <option {{'selected' if request.args.get('order')=="asc" }} value="asc">+</option>
                <option {{'selected' if request.args.get('order')=="desc" }} value="desc">-</option>
            </select>
        </div>
        <div class="col-12">
            <label class="form-label" for="limit">Limit</label>
            <input class="form-control" type="number" min="1" max="100" id="limit" name="limit"
                value="{{request.args.get('limit') or '10'}}" />
        </div>
        <div class="col-12">
            <!-- hack to align button with inputs in inline form with labels-->
            <div>&nbsp;</div>
            <button type="submit" class="btn btn-primary mt-2">Filter</button>
            <!--trick to reset a prefilled form to empty-->
            <a href="?" class="btn btn-secondary mt-2">Reset</a>
        </div>
    </form>
    <table class="table">
        {% if resp and resp|length > 0 %}
        <thead>
            <tr class="text-capitalize">
                {% for r in resp[0] %}
                <th>{{r}}</th>
                {% endfor %}
            </tr>
        </thead>
        {% for r in resp %}
        <tr>
            {% for v in r.values() %}
            <td>{{v}}</td>
            {% endfor %}
            <td><a href="{{url_for('sample.edit', id=r.get('id'))}}" class="btn btn-secondary btn-sm">Edit</a>
                {# **request.args spreads the key value pairs to be part of the url#}
                {# the idea is to pass it to the next route #}
                <a href="{{url_for('sample.delete', id=r.get('id'), **request.args)}}"
                    class="btn btn-danger btn-sm">x</a>
            </td>
        </tr>
        {% endfor %}
        {% else %}
        <p>No results to show</p>
        {% endif %}
</div>
{% if error %}
{{error}}
{% endif %}
</div>
{% endblock %}

flask_sample/templates/nav.html
{% from "_dropdown_nav.html" import dropdown_nav %}
<nav class="navbar navbar-expand-lg bg-grey">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('auth.landing_page') }}">
            <img src="https://store-images.s-microsoft.com/image/apps.51017.13510798886741797.40e62e3b-6f16-46fa-9323-15ebc223229d.5f19fe95-4a73-40cc-ba39-9f7c21f932bb" alt="Deezer Logo" width="30" height="30">
            Deezer
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                {% if not current_user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('auth.login')}}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('auth.register')}}">Register</a>
                </li>
                {% else %}
                
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('auth.profile')}}">Profile</a>
                </li>
                <!-- samples nav -->
                {% set samples = [
                ("sample.add", "Add"),
                ("sample.list", "List"),
                ] %}
                {{dropdown_nav("Samples", samples)}}


                <!-- roles nav (requires admin )-->
                {% if current_user.has_role("Admin") %}
                {% set roles = [
                ("roles.add", "Add"),
                ("roles.list", "List"),
                ("roles.assign", "Assign")
                ] %}
                {{dropdown_nav("Roles", roles)}}
                {% endif %}

                {% set tracks = [
                    ("tracks.list", "List"),
                ] %}
                {{dropdown_nav("Tracks", tracks)}}

                {% set tracks = [
                    ("tracks.list_playlist", "List Playlist"),
                ] %}
                {{dropdown_nav("Playlists", tracks)}}

                {% if current_user.has_role("Admin") %}
                    {% set admin_menu = [
                        ("tracks.list_users", "List Users"),
                        ("tracks.list_tracks_in_user_playlists", "User Tracks")
                    ] %}
                    {{ dropdown_nav("Users", admin_menu) }}
                {% endif %}

                

                {% if current_user.has_role("Admin") %}
                {% set tracks = [
                ("tracks.fetch", "Fetch"),
                ("tracks.add", "Add"),
                ] %}
                {{dropdown_nav("Tracks Data", tracks)}}
                {% endif %}
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link"
                        href="{{url_for('auth.logout')}}">Logout</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

flask_sample/templates/sort_filter.html
{# TODO DO NOT EDIT #}
{% macro sort_filter(cols=[]) %}
<div class="col">
    <label class="visually-hidden" for="col">Field</label>
    <select class="form-select" id="col" name="column"
        value="{{request.args.get('column', '')}}">
        <option value="">Field...</option>
        {# hint expects a list of tuples representing (value, label) #}
        {% for v,l in cols %}
        <option {{'selected' if v==request.args.get('column', '' )}}
            value="{{v}}">{{l | capitalize}}</option>
        {% endfor %}
    </select>
</div>
<div class="col">
    <label class="visually-hidden" for="order">Order</label>
    <select class="form-select" id="order" name="order"
        value="{{request.args.get('order', 'asc')}}">
        <option {{'selected' if request.args.get('order')=='asc' }} value="asc">
            Up</option>
        <option {{'selected' if request.args.get('order')=='desc' }}
            value="desc">Down</option>
    </select>
</div>
{% endmacro %}